name = "raffle-leader-blog"

[build]
command = '''
cd app && \
curl -sSL https://get.wasp-lang.dev/installer.sh | sh && \
wasp build && \
cd .wasp/build/web-app && \
npm install && \
REACT_APP_API_URL=https://raffleleader.fly.dev \
REACT_APP_GOOGLE_ANALYTICS_ID=G-07KK6B93ZM \
REACT_APP_STRIPE_CUSTOMER_PORTAL=https://billing.stripe.com/p/login/3cs2bl4oD2rGcYo3cc \
npm run build && \
cd ../../../../.. && \
cd blog && \
npm install && \
npm run build && \
mkdir -p ../app/.wasp/build/web-app/build/blog && \
cp -r build/* ../app/.wasp/build/web-app/build/blog/
'''
pages_build_output_dir = "app/.wasp/build/web-app/build"