name = "raffle-leader"
type = "javascript"
compatibility_date = "2024-09-05"

# Define the Node.js version explicitly
build.command = "npm install && npm run build"
build.environment = { NODE_VERSION = "18.18.0" }